Feature: TEMPLATE FEATURE

    #==============SOME DYNAMIC STEP===========================
  Scenario: Template Dynamic Step
    #TEXTBOX
    And I INPUT TO TEXTBOX BY ID "123" WITH DATA "123"
    And I INPUT TO TEXTBOX BY NAME "123" WITH DATA "123"
    And I INPUT TO TEXTBOX BY FORMCONTROLNAME "123" WITH DATA "123"
    And I INPUT TO TEXTBOX BY PLACEHOLDER "123" WITH DATA "123"
    And I INPUT TO TEXTBOX BY VALUE "123" WITH DATA "123"
    And I INPUT TO TEXTBOX BY FORMCONTROLNAME "123" WITH DATA "123"
    And I CLICK TO TEXTBOX BY ID ""
    And I CLICK TO TEXTBOX BY NAME ""
    And I CLICK TO TEXTBOX BY CONTAINS TEXT ""
    And I CLICK TO TEXTBOX BY TEXT ""
    And I CLICK TO TEXTBOX BY VALUE ""
    #BUTTON
    And I CLICK TO BUTTON BY ID ""
    And I CLICK TO BUTTON BY VALUE ""
    And I CLICK TO BUTTON BY NAME ""
    And I CLICK TO BUTTON BY TITLE ""
    And I CLICK TO BUTTON BY CONTAINS TEXT ""
    And I CLICK TO BUTTON BY SPAN TEXT ""
    And I CLICK TO BUTTON BY SPAN CONTAINS TEXT ""
    #ITEM
    And I Open "Properties" page
    And I CLICK TO ITEM BY CONTAIN TEXT ""
    #LINK
    And I CLICK TO LINK BY CONTAIN TEXT ""
    #ALERT
    And CLICK TO DIV ALERT BY CONTAINS TEXT "Success"
    And CLICK TO ITEM ALERT BY CONTAINS TEXT "Success"
    #
    #VERIFY
    And VERIFY ITEM BY CONTAINS TEXT WITH MESSAGE "" DISPLAYED SUCCESS
    And VERIFY LINK BY CONTAINS TEXT WITH MESSAGE "" DISPLAYED SUCCESS
    And VERIFY DIV BY CONTAINS TEXT WITH MESSAGE "" DISPLAYED SUCCESS
